### ISSUE TITLE
Allow configuration of the API Key through an argument

### ISSUE THREAD

**Issue by HenriBeck** [newrelic/opentelemetry-exporter-go#45]
Right now the users are forced to configure the API Key for the export pipeline through the `NEW_RELIC_API_KEY`.

This however can complicate the setup for some users as they might not use environment variables for secret sharing, but a Vault or some other method. Right now we are working around this limitation with the following code:
```go
// Set the api key to the OS environment variables as the new relic exporter depends on this.
os.Setenv("NEW_RELIC_API_KEY", newRelicAPIKey)
defer os.Setenv("NEW_RELIC_API_KEY", "")
```

It would be great if you could also support a functional options pattern similar to the one shown by the [newrelic-go-agent](https://github.com/newrelic/go-agent/blob/master/v3/newrelic/config_options.go#L29) for configuring such things.

**Comment by RichVanderwal** [comment]
Hello again, @HenriBeck ! 

It's true, the convenience function `NewExportPipeline` relies on environment variables for configuration. You'll have more flexibility if you just use `NewExporter` instead, giving you the ability to do other important things like turn on logging in your exporter:
```
	exporter, err := newrelic.NewExporter(
		"Sample OpenTelemetry Service Exporter",
		apiKey,
		telemetry.ConfigBasicErrorLogger(os.Stderr),
		telemetry.ConfigBasicDebugLogger(os.Stderr),
		telemetry.ConfigBasicAuditLogger(os.Stderr),
	)
	if err != nil {
		fmt.Printf("failed to instantiate exporter: %v\n", err)
	}
``` 

Since `NewExportPipeline` set up your tracer and pusher for you, you'll need to do this in your code, too.

There's a "Getting Started" guide for the New Relic OpenTelemetry Exporter for Go coming soon. Let us know if you have any other questions!

**Comment by HenriBeck** [comment]
@RichVanderwal yeah, we pretty much just copied the code from [NewExportPipeline](https://github.com/newrelic/opentelemetry-exporter-go/blob/master/newrelic/exporter.go#L89).

It would still be great to be able to use `NewExportPipeline` or `InstallNewPipeline` and being able to configure them a bit more than it's currently possible.

**Comment by Ak-x** [comment]
We have closed this issue as a work-around was achieved.
